### ISSUE TITLE
Matching

### ISSUE THREAD

**Issue by yiyihao2000** [yosungho/LineTR#15]
Hello, your work is excellent. I have a question to ask you. May I ask how you match the line descriptors after Line Signature Networks? What network or method is used?Thanks。

**Comment by yosungho** [comment]
Sure. Since the model is making descriptors, you can match the lines with common nearest-neighbor (NN) matchings that many point-based descriptors also use. You can also use it with mutual NN, and w/ a ratio test, etc, and the code is using a mutual NN (https://github.com/yosungho/LineTR/blob/2ed4b4078ce76a051103ce03c8744580abf9ce5e/models/nn_matcher.py#L3).
